export enum DbTable {
  category = 'category',
  comment = 'comment',
  crawl_history = 'crawl_history',
  master_country = 'master_country',
  master_gender = 'master_gender',
  notification = 'notification',
  post = 'post',
  post_interaction = 'post_interaction',
  post_tag = 'post_tag',
  reason_report = 'reason_report',
  recently_view_posts = 'recently_view_posts',
  setting_element = 'setting_element',
  setting_page = 'setting_page',
  setting_web = 'setting_web',
  tag = 'tag',
  user = 'user',
}