export enum API {
  BASE_URL = 'http://localhost:8000',
  SETTING_WEB = '/setting-web',
  SETTING_PAGE_LIST = '/setting-web',
  SETTING_PAGE_DETAIL = '/setting-page',
  TAG = '/tag',
  COUNTRY = '/country',
  GENDER = '/gender',
  CATEGORY_ALL = '/category/all',
  CATEGORY= '/category',
  DATA = '/data',
  SETTING_WEB_SAVE = '/setting-web/save',
  POST = '/post',
  POST_ACTIVE = '/post/active',
  POST_DEACTIVE = '/post/deactive',
  REPORT = '/report/sum',
  REPORT_SAVE = '/report',
  REPORT_DETAIL = '/report',
  NOTIFICATION = '/notification',
  USER = '/user',
  DASHBOARD = '/dashboard',
  LOGIN = '/login',
  REGISTER = '/register',
  COMMENT = '/comment',
  INFO = '/info',
  AVATAR = '/user/avatar',
  REASON = '/reason',
};
